name: flowsense
description: A Flutter app for mood and wellness tracking.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Ads
  google_mobile_ads: ^6.0.0
  local_auth: ^2.3.0

  # Routing package
  go_router: ^16.0.0

  # Firebase Core
  firebase_core: ^4.0.0

  # Firebase Authentication
  firebase_auth: ^6.0.1
  
  # Google Sign-In
  google_sign_in: ^7.1.1
  
  # Apple Sign-In
  sign_in_with_apple: ^7.0.1

  # Cloud Firestore (for period tracking data)
  cloud_firestore: ^6.0.0
  
  # Firebase Analytics (for enterprise monitoring)
  firebase_analytics: ^12.0.0
  
  # Firebase Crashlytics (for error reporting)
  firebase_crashlytics: ^5.0.0
  
  # Firebase Performance (for performance monitoring)
  firebase_performance: ^0.11.0

  # State management
  provider: ^6.1.2

  # Local storage for settings
  shared_preferences: ^2.3.4

  # File handling and sharing
  path_provider: ^2.1.5
  share_plus: ^11.1.0
  file_picker: ^10.3.2
  permission_handler: ^12.0.1
  
  # Network connectivity
  connectivity_plus: ^6.1.1
  
  # Database for caching
  sqflite: ^2.4.1
  path: ^1.9.1
  
  # HTTP requests
  http: ^1.2.2
  
  # Firebase Storage
  firebase_storage: ^13.0.0
  
  # URL Launcher
  url_launcher: ^6.3.1
  
  # Encryption
  crypto: ^3.0.6
  
  # Image processing and picking
  image_picker: ^1.0.7
  image: ^4.1.7

  # JSON handling
  csv: ^6.0.0

  # Calendar view
  table_calendar: ^3.2.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.0
  
  # Charts for provider dashboard
  fl_chart: ^1.0.0
  
  # PDF generation for reports
  pdf: ^3.11.1
  
  # Health platform integration (using custom implementation)
  # health: ^13.1.1  # Removed to avoid minSdk conflicts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  
  # Testing dependencies
  fake_cloud_firestore: ^4.0.0
  firebase_auth_mocks: ^0.15.0
  mockito: ^5.4.3
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#FCE4EC"
    theme_color: "#E91E63"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"
